---
- name: get subnet01
  ec2_vpc_subnet_facts:
    region: "{{ aws.common.region }}"
    filters:
      "tag:Name": "{{ aws.vpc.pubsubnet.subnet01.tags.Name }}"
  register: elb_subnet01_facts
  check_mode: no

- name: get subnet02
  ec2_vpc_subnet_facts:
    region: "{{ aws.common.region }}"
    filters:
      "tag:Name": "{{ aws.vpc.pubsubnet.subnet01.tags.Name }}"
  register: elb_subnet02_facts
  check_mode: no

- name: Create ELB
  ec2_elb_lb:
    name: "{{ aws.elb.name }}"
    state: present
    region: "{{ aws.common.region }}"
    subnets:
      - "{{ elb_subnet01_facts.subnets.id }}"
      - "{{ elb_subnet02_facts.subnets.id }}"
    listeners:
      - protocol: http
        load_balancer_port: 80
        instance_port: 80
